spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/content_analyzer?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

logging:
  level:
    root: INFO
    com.nextpost: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

server:
  port: 8081

youtube:
  application-name: Content Analyzer
  api-key: AIzaSyCiDTN5Y3PO5XdVOkELQwX4HIcwQyhDB4M
  analytics:
    client-id: 697477926678-ph2osiscru7pihqis9jqmnirbrfner8f.apps.googleusercontent.com
    client-secret: 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
