version: '3.8'

services:
  app:
    image: eclipse-temurin:21-jdk
    container_name: ca_youtube-app
    working_dir: /app
    volumes:
      - .:/app
      - gradle-cache:/root/.gradle
    command: ["./gradlew", "clean", "build", "-x", "check", "-x", "test"]
    depends_on:
      - postgres
    networks:
      - ca_youtube-network

  postgres:
    image: postgres:16-alpine
    container_name: ca_youtube-db
    environment:
      POSTGRES_DB: ca_youtube
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - ca_youtube-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  ca_youtube-network:
    driver: bridge

volumes:
  postgres-data:
  gradle-cache:
